ALTER TYPE "RideRequestStatus" ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE "RideRequestStatus" ADD VALUE IF NOT EXISTS 'OFFERING';
ALTER TYPE "RideRequestStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "RideRequestStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "RideRequestStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';

ALTER TYPE "RideRequestOfferStatus" ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE "RideRequestOfferStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "RideRequestOfferStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "RideRequestOfferStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
